# Generated by Django 3.0.7 on 2020-08-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('heah0', models.CharField(max_length=500)),
                ('cheah0', models.CharField(max_length=5000)),
                ('heah1', models.CharField(max_length=500)),
                ('cheah1', models.CharField(max_length=5000)),
                ('heah2', models.CharField(max_length=500)),
                ('cheah2', models.CharField(max_length=5000)),
                ('pub_date', models.DateField()),
                ('thumbnail', models.ImageField(upload_to='shop/images')),
            ],
        ),
    ]
